### ISSUE TITLE
Investigation?

### ISSUE THREAD

**Issue by rpovelik** [tstarling/thread-safe-lru#1]
Hi Tim,

I found your project and I'm trying to find out some possible pros and cons for different situations and just want to ask you about `tbb::concurrent_lru_cache`. Did you try to reuse or investigate such container which is currently in preview features of the library bit that was announced even before your implementations as far as I know.

So if you can share some information with me - that would be great!

Thank you 😄

**Comment by tstarling** [comment]
Documentation for the community preview features indicated that the API for those features was unstable, and they may be deleted in future without warning. For HHVM I needed a container with a stable API. I didn't think a PR which attempted to pull in a community preview feature would be accepted. Also, I reviewed the `tbb::concurrent_lru_cache` source code, and I wasn't particularly impressed by the implementation. I suspected (but did not confirm) that my container would have better performance at high concurrency.

**Comment by tstarling** [comment]
Refreshing my memory now, looking at the source -- it seemed more like a demo for the *aggregator* community preview feature rather than an honest effort to produce a good LRU container. And in case you were thinking of bundling the source in order to stabilize the API, it uses things from the `tbb::internal` namespace, especially `tbb::internal::aggregating_functor` and `tbb::internal::aggregator`, which means that you can't really distribute `concurrent_lru_cache` separately from the rest of TBB.
