### ISSUE TITLE
Potential deadlock - insert and evict acquire the same accessor

### ISSUE THREAD

**Issue by jy5275** [tstarling/thread-safe-lru#5]
In `insert` method, under hight concurrent cases, it possible for a thread to evict the node that was just inserted by the same call.
So the thread at A tries to acquire the accessor that it already taken at B:
A: https://github.com/tstarling/thread-safe-lru/blob/master/thread-safe-lru/lru-cache.h#L387
B: https://github.com/tstarling/thread-safe-lru/blob/master/thread-safe-lru/lru-cache.h#L281
which cause deadlock

**Comment by tstarling** [comment]
Any chance of a PR?

**Comment by jy5275** [comment]
> Any chance of a PR?

Please review https://github.com/tstarling/thread-safe-lru/pull/6

**Comment by tstarling** [comment]
Thanks @jy5275! I didn't test it, but I did stare at it until I spotted the potential deadlock you're referring to.

I'm not really using this code now, since I wrote it for HHVM, but HHVM later abandoned PHP compatibility and we (Wikimedia) undeployed it and dropped support. Facebook are apparently still using it though (https://github.com/facebook/hhvm/blob/master/hphp/util/concurrent-lru-cache.h), so I'll forward the issue to them out of courtesy.
